# Generated by Django 4.1.10 on 2023-09-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_auther_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
