# Generated by Django 4.1.10 on 2023-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('shop', '0003_remove_product_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whislist',
            field=models.ManyToManyField(to='vendor.vendor'),
        ),
    ]
