# Generated by Django 4.1.10 on 2023-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('shop', '0005_alter_product_whislist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whislist',
            field=models.ManyToManyField(blank=True, related_name='whislist', to='vendor.vendor'),
        ),
    ]
