# Generated by Django 4.1.10 on 2023-09-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('shop', '0009_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendor.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('vendor', 'product')},
        ),
    ]
