# Generated by Django 4.1.10 on 2023-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_wishlistitem_product_alter_wishlistitem_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, upload_to='product/'),
        ),
    ]
