# Generated by Django 4.1.10 on 2023-09-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productimage_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
