# Generated by Django 4.1.10 on 2023-09-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Images',
        ),
    ]
