# Generated by Django 4.2.2 on 2023-09-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_productimage_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ProductImages',
        ),
    ]
